/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CommandResult } from "./yabai/yabai-service";
export { CommandResult } from "./yabai/yabai-service";
export namespace Components {
    interface AppDashboard {
    }
    interface CliRoot {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface YabaiGui {
        /**
          * @default 'v7.1.17'
         */
        "version": string;
    }
}
export interface YabaiGuiCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYabaiGuiElement;
}
declare global {
    interface HTMLAppDashboardElement extends Components.AppDashboard, HTMLStencilElement {
    }
    var HTMLAppDashboardElement: {
        prototype: HTMLAppDashboardElement;
        new (): HTMLAppDashboardElement;
    };
    interface HTMLCliRootElement extends Components.CliRoot, HTMLStencilElement {
    }
    var HTMLCliRootElement: {
        prototype: HTMLCliRootElement;
        new (): HTMLCliRootElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLYabaiGuiElementEventMap {
        "commandExecuted": CommandResult;
    }
    interface HTMLYabaiGuiElement extends Components.YabaiGui, HTMLStencilElement {
        addEventListener<K extends keyof HTMLYabaiGuiElementEventMap>(type: K, listener: (this: HTMLYabaiGuiElement, ev: YabaiGuiCustomEvent<HTMLYabaiGuiElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLYabaiGuiElementEventMap>(type: K, listener: (this: HTMLYabaiGuiElement, ev: YabaiGuiCustomEvent<HTMLYabaiGuiElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLYabaiGuiElement: {
        prototype: HTMLYabaiGuiElement;
        new (): HTMLYabaiGuiElement;
    };
    interface HTMLElementTagNameMap {
        "app-dashboard": HTMLAppDashboardElement;
        "cli-root": HTMLCliRootElement;
        "my-component": HTMLMyComponentElement;
        "yabai-gui": HTMLYabaiGuiElement;
    }
}
declare namespace LocalJSX {
    interface AppDashboard {
    }
    interface CliRoot {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface YabaiGui {
        "onCommandExecuted"?: (event: YabaiGuiCustomEvent<CommandResult>) => void;
        /**
          * @default 'v7.1.17'
         */
        "version"?: string;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface YabaiGuiAttributes {
        "version": string;
    }

    interface IntrinsicElements {
        "app-dashboard": AppDashboard;
        "cli-root": CliRoot;
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "yabai-gui": Omit<YabaiGui, keyof YabaiGuiAttributes> & { [K in keyof YabaiGui & keyof YabaiGuiAttributes]?: YabaiGui[K] } & { [K in keyof YabaiGui & keyof YabaiGuiAttributes as `attr:${K}`]?: YabaiGuiAttributes[K] } & { [K in keyof YabaiGui & keyof YabaiGuiAttributes as `prop:${K}`]?: YabaiGui[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-dashboard": LocalJSX.IntrinsicElements["app-dashboard"] & JSXBase.HTMLAttributes<HTMLAppDashboardElement>;
            "cli-root": LocalJSX.IntrinsicElements["cli-root"] & JSXBase.HTMLAttributes<HTMLCliRootElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "yabai-gui": LocalJSX.IntrinsicElements["yabai-gui"] & JSXBase.HTMLAttributes<HTMLYabaiGuiElement>;
        }
    }
}
